version: '3'
services:
  kafka1:
    image: registry.cn-hangzhou.aliyuncs.com/yangyuanpeng/kafka:5.1.0.1
    environment:
      - TZ=Asia/Shanghai
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.200.80:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_NUM_PARTITIONS=8
      - KAFKA_DEFAULT_REPLICATION_FACTOR=2
    volumes:
      - kafka1data:/var/lib/kafka/data
      - /etc/localtime:/etc/localtime
      - kafka1secrets:/etc/kafka/secrets
      - kafka1logs:/var/log/kafka-server-logs
      - kafka1GClogs:/var/log/kafka
    ports:
      - "9092:9092"
    networks:
      - kafka_net


volumes:
  kafka1data:
  kafka1secrets:
  kafka1logs:
  kafka1GClogs:
networks:
  kafka_net:
    external: true
