version: '3'
services:
  kafka3:
    image: registry.cn-hangzhou.aliyuncs.com/yangyuanpeng/kafka:5.1.0.1
    environment:
      - TZ=Asia/Shanghai
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.200.80:9094
      - KAFKA_BROKER_ID=3
      - KAFKA_NUM_PARTITIONS=8
      - KAFKA_DEFAULT_REPLICATION_FACTOR=2
    volumes:
      - kafka3data:/var/lib/kafka/data
      - /etc/localtime:/etc/localtime
      - kafka3secrets:/etc/kafka/secrets
      - kafka3logs:/var/log/kafka-server-logs
      - kafka3GClogs:/var/log/kafka
    ports:
      - "9094:9094"
    networks:
      - kafka_net


volumes:
  kafka3data:
  kafka3secrets:
  kafka3logs:
  kafka3GClogs:
networks:
  kafka_net:
    external: true
